### ISSUE TITLE
Running `boot(IntercomProps)` results in unknown user

### ISSUE THREAD

**Issue by tplante** [devrnt/react-use-intercom#563]
**Describe the bug**
Using the `boot` method with user information results in an unknown user. 

**To Reproduce**
❌
```
const { boot } = useIntercom()
const user = {
  userId: '1234',
  email: 'user@user.com',
}
boot(user)
```

With this code, if I run `intercomSettings` in the browser terminal, an unknown user has been initialized. This can be fixed by running `boot` without `IntercomProps` and instead passing them to `update`:

✅
```
const { boot, update } = useIntercom()
const user = {
  userId: '1234',
  email: 'user@user.com',
}
boot()
update(user)
```

**Expected behavior**
I would expect that `boot(IntercomProps)` both initializes intercom _and_ updates user details. Why allow user details to be passed to this method if it does not update the user?

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome
 - Version: 2.0.0

**Comment by devrnt** [comment]
Thanks for creating this issue, this is indeed not expected behaviour.

However, I can't reproduce your issue. There is an [example that boots with some props](https://devrnt.github.io/react-use-intercom/#/useIntercom) ("Boot props" action). As aspected, the initial `window.intercomSettings` object is undefined, after booting, it has the `{app_id: 'jcabc7e3', name: 'Russo'}` value.

Could you provide a codesandbox with a reproduction?

**Comment by devrnt** [comment]
Makes sense. There is no caching here, `boot` can only be called once (as the method indicates). After booting you should call `update` as [mentioned here](https://developers.intercom.com/installing-intercom/docs/intercom-javascript#intercomupdate)

Hope this helps!

**Comment by tplante** [comment]
Thanks! My oversight, this is resolved then.
